### ISSUE TITLE
Work through "from 0 to proving with K" video

### ISSUE THREAD

**Issue by ehildenb** [kframework/evm-semantics#1010]
The video documents the process of starting from an empty file and working up towards doing small proofs. The exercises come from here: https://github.com/ehildenb/understanding-k-framework

Complete the exercises, looking at the solutions as little as possible. Make sure you understand the point of each exercise (in terms of what it teaches you about K).

Make sure you can run the proofs at the end with the Haskell backend, and can step through their execution with the debugger.

### Max

- [x] 0 to proving with K video 1: https://www.youtube.com/watch?v=QHsERS1PyXk
- [x] 0 to proving with K video 2: https://www.youtube.com/watch?v=aRvYFAcKdD4
- [x] Can build all the specifications there.
- [x] Can run all the tests there (including the proofs).
- [x] Can run the kore-repl on a proof and step through the execution.
- [x] Discussion about the semantics and the proofs.

### Henry

- [x] 0 to proving with K video 1: https://www.youtube.com/watch?v=QHsERS1PyXk
- [x] 0 to proving with K video 2: https://www.youtube.com/watch?v=aRvYFAcKdD4
- [x] Can build all the specifications there.
- [x] Can run all the tests there (including the proofs).
- [x] Can run the kore-repl on a proof and step through the execution.
- [x] Discussion about the semantics and the proofs.

**Comment by JKTKops** [comment]
Running kprove on `simple-spec.k` produces this warning:
```
$ kprove simple-spec.k
kore-exec: [1206880] Warning (WarnStuckClaimState):
    (InfoReachability) while checking the implication:
    The proof has reached the final configuration, but the claimed implication is not valid. Location: /home/jktkops/runtimeverification/k-tutorial/1-basic/0-to-proving/././simple-spec.k:49:9-56:65
  #Not ( {
    M [ $a <- A:Int ] [ $b <- B:Int ] [ $c <- maxInt ( A , B ) ]
  #Equals
    M [ $a <- A:Int ] [ $b <- B:Int ] [ $c <- B:Int ]
  } )
#And
  <generatedTop>
    <k>
      _DotVar1
    </k>
    <mem>
      M [ $a <- A:Int ] [ $b <- B:Int ] [ $c <- B:Int ]
    </mem>
  </generatedTop>
#And
  {
    true
  #Equals
    A <Int B
  }
```
In the REPL, the proof branches and a similar warning appears at the end of both branches.

**Comment by Riib11** [comment]
I also get this same warning

**Comment by ehildenb** [comment]
I found the problem! We're doing `kprove tests/control-flow/simple-spec.k`, which uses the `--def-module/-m` which is the main module of the original definition, _not_ the `VERIFICATION` module from the proof.

You'll need to do instead `kprove tests/control-flow/simple-spec.k -m VERIFICATION`, which tells it to use `VERIFICATION` as the main module (and thus to include those lemmas).
