### ISSUE TITLE
Inspect lemmas in `tests/specs/lemmas.k` and `tests/specs/benchmarks/verification.k` for duplicates/generalizations

### ISSUE THREAD

**Issue by ehildenb** [kframework/evm-semantics#1024]

**Comment by Riib11** [comment]
In `tests/specs/benchmarks/verification.k`, replace

```
rule #take(#sizeWordStack(WS:WordStack, 0), WS) => WS
      [simplification]
```

with

```
rule WS [ 0 .. #sizeWordStack(WS:WordStack, 0) ] => WS
      [simplification]
```

since using `#take` in a lemma is bad, since it is backend-specific.

Still need to test whether this breaks any proofs.

**Comment by ehildenb** [comment]
Add the rule `EVM-TYPES.ByteArray.range` to all teh concrete-rules files, and try running the proof without that `#take` lemma.

Are there any other lemmas with `#take` in them anywhere else in the `tests/specs` directory? `git grep '#take' -- tests/specs` to find out.

**Comment by Riib11** [comment]
After removing the lemma
```
rule #take(#sizeWordStack(WS:WordStack, 0), WS) => WS
      [simplification]
```
from `tests/specs/benchmarks/verification.k`, adding the rule `EVM-TYPES.ByteArray.range` to all the concrete-rules files and running `make test-prove-benchmarks TEST_SYMBOLIC_BACKEND=haskell -j8`, all the tests still pass. This indicates the the lemma was not actually being used. I'll look for other lemmas that use `#take`.

**Comment by Riib11** [comment]
The only other file that has lemmas that refer to `#take` is `tests/specs/lemmas.k`. I'll run a test to see if these are safe to remove, but my guess is that they are not since `lemmas.k` has backend-specific lemmas.

**Comment by Riib11** [comment]
Looks like everything in `make test-prove` passes still! So none of the `#take` lemmas were needed. Next I will do the same with `#drop`.

**Comment by Riib11** [comment]
Still works after lemmas using `#drop` are removed

**Comment by Riib11** [comment]
#1068 prunes some lemmas from `tests/specs/lemmas.k` and `tests/specs/benchmarks/verification.k`

**Comment by Riib11** [comment]
Work for this issue is now on branch [generalize-haskell-lemmas-benchmarks](https://github.com/kframework/evm-semantics/tree/generalize-haskell-lemmas-benchmarks)
