### ISSUE TITLE
Remove unused `#take` lemmas

### ISSUE THREAD

**Issue by ehildenb** [kframework/evm-semantics#1062]
We should not have any lemmas about `#take` or `#drop`, instead they should be over `_[_.._]`.

This also means that we need to make sure that all the `concrete-rules.txt` files contain BOTH rules (for the java and haskell backends).

The rules are in `evm-types.md`.

**Comment by Riib11** [comment]
(As in #1024)

After these changes:
- disabled all lemmas in `tests/specs/lemmas.k` and `tests/specs/benchmark/verification.k` that use either `#take` or `#drop`
- added `ByteArray.range` and `bytesRange` to all `concrete-rules.txt` files

The result is that `make test-prove TEST_SYMBOLIC_BACKEND=haskell` still passes! This indicates the those lemmas are not being used at all after the rules that consume `#take` and `#drop` were concretized. No new lemmas over `_[_.._]` were needed.
