### ISSUE TITLE
Organize lemma files

### ISSUE THREAD

**Issue by ehildenb** [kframework/evm-semantics#1071]
Each of the individual lemmas file have a bunch of un-organized lemmas which makes it harder to spot generalizations.

Let's re-organize them, making sure to group lemmas by the top symbol on the LHS of the lemma (eg. the top symbol of `#range(X [ K <- V ], START, WIDTH)` would be `#range`. This should make it easier to spot potential generalizations.

Let's also format them while we're at it, to make it easier to spot the generalizations.

Do _not_ also make changes to the contents of the lemmas themselves. Strictly formatting and organization.

**Comment by Riib11** [comment]
By "the lemmas files" you mean `tests/specs/lemmas.k` and `tests/specs/**/verification.k`, right?

**Comment by Riib11** [comment]
Work in branch [organize-lemmas](https://github.com/kframework/evm-semantics/tree/organize-lemmas)

**Comment by ehildenb** [comment]
Yep, all the lemmas files.
