### ISSUE TITLE
Pull out `tests/specs/int-simplification.k`

### ISSUE THREAD

**Issue by ehildenb** [kframework/evm-semantics#1086]
Lots of the lemmas files/verificaiton files have integer simplification routines, including things which dictate how we re-associate integer terms.

I would recommend starting by pulling out the integer simplification stuff from `tests/specs/infinite-gas.k` into `tests/specs/int-simplification.k`, and making sure tests pass with that refactoring. Then pull out the integer simplification stuff from `tests/specs/lemmas.k` (which you likely just need to delete things there, not migrate anything), and make tests pass again (by including `tests/specs/int-simplification` into `tests/specs/lemmas.k`).

Finally go through each verification file and remove integer simplification lemmas, making sure that the given test-suite passes with the update.

Ideally we would end up with just one file which contains all the integer simplifications. Note that both arithmetic operators and comparison operators (eg. `_<=Int_`) can be included in this file. Also don't forget things like `modInt` or `^Int` or any pure integer + comparison operators.

But anything specific to KEVM (eg. `#lookup(...)` or `chop(...)` should not be moved).

**Comment by Riib11** [comment]
Integer-related lemmas to pull out use:
- Int arithmetic operations: `+Int`, `-Int`, `*Int`, `modInt`, `^Int`
- Int comparisons: `<Int`, `<=Int`, `>=Int`, `>Int`

Integer-related lemmas to __not__ pull out use:
- anything specific to KEVM e.g. `#lookup`, `chop`

**Comment by Riib11** [comment]
@ehildenb Should I also include `#range(...)`, `#rangeUInt(...)`, etc. lemmas in INT-SIMPLIFICATION?
