### ISSUE TITLE
Self modifying code?

### ISSUE THREAD

**Issue by fulldecent** [kframework/evm-semantics#129]
Issues.md states:

> Currently in EVM, the *CODECOPY opcodes allow regarding program pieces as data, meaning that a translation back must always be maintained, because in theory a program can modify itself while executing.

The machine state (including memory) is defined in "9.4.1. Machine State" and the execution environment (including program code) is "9.3. Execution Environment."

CODECOPY is defined in the OPCODES table and brings code from the latter to the former.

How are you seeing that a program can modify itself?

**Comment by ehildenb** [comment]
programs can't modify themselves, but the point still remains that a translation back to bytecode representation must be maintained for EVM execution (which makes reasoning about EVM code more difficult).

**Comment by fulldecent** [comment]
Understood, thank you. 

Perhaps that line and the following can be improved. Such can be the scope of this issue.

> While self-modifying code is nice and powerful in principle, we are not aware of any programming languages for the blockchain that encourage or even allow that.

**Comment by fulldecent** [comment]
Also, yes, difficult to reason.

FYI, here's is a (limited) Solidity decompiler I am writing. It runs *on* the blockchain.

https://github.com/ethereum/EIPs/issues/165#issuecomment-361804759

Thought you might get a laugh out of that.

**Comment by dwightguth** [comment]
Another point of view to consider is that while a contract cannot modify itself, it can construct an arbitrary fragment of code, CREATE it as a new contract, and then DELEGATECALL the contract it created to effectively execute arbitrary code. So I'm honestly not sure it's correct to claim that evm doesn't support self modifying code.

**Comment by fulldecent** [comment]
Fair enough, can execute arbitrary code. I suggested a slightly different wording here.

Fun stuff to look at for sure!
