### ISSUE TITLE
Signature extraction rules - D needs to be power of 256 and not just multiple of 256

### ISSUE THREAD

**Issue by AlexeyAkhunov** [kframework/evm-semantics#145]
in verification.md, there is a non-critical mistake in the description of the signature extraction:

    // for Solidity

    rule #asWord(WS) /Int D => #asWord(#take(#sizeWordStack(WS) -Int log256Int(D), WS))

      requires D modInt 256 ==Int 0 andBool D >=Int 0

       andBool #sizeWordStack(WS) >=Int log256Int(D)

       andBool #noOverflow(WS)

the requirement needs to be not just that D is a multiple of 256, but that it is a power of 256 (then log256Int will correspond to the number of bytes to shift by). I am not sure how to express it yet though.

**Comment by dwightguth** [comment]
@daejunpark can you take a look?

**Comment by daejunpark** [comment]
@AlexeyAkhunov good catch! thanks a lot for reporting this! there are several options to express the power of 256. we will fix this probably next week.

**Comment by ehildenb** [comment]
@daejunpark can you close if this is taken care of?

**Comment by daejunpark** [comment]
@ehildenb sorry, not yet. will close once i'm done.

**Comment by daejunpark** [comment]
Since the code is moved to another repo, I close this via https://github.com/runtimeverification/verified-smart-contracts/issues/9
