### ISSUE TITLE
README: nonexistent argument of ./kevm prove

### ISSUE THREAD

**Issue by pirapira** [kframework/evm-semantics#159]
When I follow the readme, I see
```
$ ./kevm prove tests/proofs/erc20/hkg/transfer-success-1-spec.k
FATAL: tests/proofs/erc20/hkg/transfer-success-1-spec.k does not exist
```
It seems like the file has moved or disappeard.

**Comment by ehildenb** [comment]
Good catch, can you add a fix to: https://github.com/kframework/evm-semantics/pull/157

**Comment by ehildenb** [comment]
The proofs submodule has a new directory structure (is the reason this became outdated)

**Comment by chenIshi** [comment]
In current README.md, 
`./kevm prove tests/proofs/specs/vyper-erc20/totalSupply-spec.k` the location should be tests/specs/......

And also I do not see the entry point of './kevm test' in `kevm` script, do ./kevm still support the usage of `test` ?
(`./kevm test tests/ethereum-tests/VMTests/vmArithmeticTest/add0.json` in README.md)
