### ISSUE TITLE
`RETURNDATACOPY` may check twice for `EVM_INVALID_MEMORY_ACCESS`

### ISSUE THREAD

**Issue by ehildenb** [kframework/evm-semantics#173]
Right now there is an extra rule for `RETURNDATACOPY` which checks for invalid memory access, but this should already be caught by the `#memory` function.

We should remove the redundant check.

**Comment by dwightguth** [comment]
I have absolutely no idea what you're talking about. This rule isn't redundant at all and has nothing to do with the gas usage captured by #memory. It is directly part of ethereum/EIPs#211. Unlike all other COPY instructions, RETURNDATACOPY throws an exception if you try to access an offset in the return data buffer that doesn't exist.

If you remove this rule and side condition, tests are definitely going to fail.

Can we close this?

**Comment by ehildenb** [comment]
Please tone down your language. I noticed what looked like a redundant rule in the semantics and opened an issue for it, it's not a cause to get mad.

I'm leaving open until I've convinced myself that this is a non-issue. I open the issue so I can keep track of things I'm not prioritizing right now but want to get to eventually.

**Comment by ehildenb** [comment]
Indeed, the checks are for different cases. Thanks @dwightguth for explaining the difference.
