### ISSUE TITLE
Cleanup control flow of existing semantics

### ISSUE THREAD

**Issue by ehildenb** [kframework/evm-semantics#177]
Currently the operator `#?_:_#?` is only used in exactly one place, meaning it should be replaced with an operator specifically for that one use. This will also simplify other parts of the code where `#pop/drop{X}` is called, allowing us to write the logic for that a single time and then the rest of the semantics simply call the macro operator.

This will take some careful doing.

**Comment by daejunpark** [comment]
Another proposal: factor out common part of `#finishTx` and `#return`.

A function is called either from a top-level transaction directly or from another function. The former is started by `startTx` followed by `loadTx`, and the latter is by `CALL`. But both will eventually reach a uniform entry point `#call`.

However, there is no uniform exit point, as the former is finalized by `#finishTx` and the latter is by `#return`, while both do the common task of pop/drop of {callStack,worldState,subState}.

This absence of the uniform exit point makes it hard to write a uniform spec of a function that can be used for both contexts. We'd like to specify like `<k> #call => ??? </k>`, but currently no `???` is available.

Below is the current definition of `#finishTx` and `#return`:

```
    syntax EthereumCommand ::= "#finishTx"
 // --------------------------------------
    rule <k> #exception ~> #finishTx => #popCallStack ~> #popWorldState ~> #popSubstate ... </k>
    rule <k> #revert    ~> #finishTx => #popCallStack ~> #popWorldState ~> #popSubstate ~> #refund GAVAIL ... </k> <gas> GAVAIL </gas>
         
    rule <k> #end ~> #finishTx => #mkCodeDeposit ACCT ... </k>
         <id> ACCT </id>
         <txPending> ListItem(TXID:Int) ... </txPending>
         <message>
           <msgID> TXID     </msgID>
           <to>    .Account </to>
           ...
         </message>

    rule <k> #end ~> #finishTx => #popCallStack ~> #dropWorldState ~> #dropSubstate ~> #refund GAVAIL ... </k>
         <id> ACCT </id>
         <gas> GAVAIL </gas>
         <txPending> ListItem(TXID:Int) ... </txPending>
         <message>
           <msgID> TXID </msgID>
           <to>    TT   </to>
           ...
         </message>
      requires TT =/=K .Account
```

```
    syntax KItem ::= "#return" Int Int
 // ----------------------------------                                                   
    rule <k> #exception ~> #return _ _
          => #popCallStack ~> #popWorldState ~> #popSubstate ~> 0 ~> #push
         ... 
         </k>
         <output> _ => .WordStack </output>
         
    rule <k> #revert ~> #return RETSTART RETWIDTH
          => #popCallStack ~> #popWorldState ~> #popSubstate
          ~> 0 ~> #push ~> #refund GAVAIL ~> #setLocalMem RETSTART RETWIDTH OUT
         ... 
         </k>
         <output> OUT </output>
         <gas> GAVAIL </gas>
         
    rule <mode> EXECMODE </mode>
         <k> #end ~> #return RETSTART RETWIDTH
          => #popCallStack
          ~> #if EXECMODE ==K VMTESTS #then #popWorldState #else #dropWorldState #fi
          ~> #dropSubstate
          ~> 1 ~> #push ~> #refund GAVAIL ~> #setLocalMem RETSTART RETWIDTH OUT
         ... 
         </k>
         <output> OUT </output>
         <gas> GAVAIL </gas>
```

**Comment by ehildenb** [comment]
I think this does fall into the same category of things I'm trying to clean up, so I will pay special attention to this issue.

**Comment by ehildenb** [comment]
Several of these cleanups have made their way in, we'll need new issues for more specific changes.
