### ISSUE TITLE
Converting negative number to two's complement representation

### ISSUE THREAD

**Issue by yzhang90** [kframework/evm-semantics#179]
Currently, evm semantics assumes that a `Word` is always a positive integer. It would be great if em-semantics can provide a function like `#signed` which takes a integer and convert it to its two's complement representation. This would be useful for implement ABI encoding for `int128` type, where the value could be either positive or negative. When the value is negative, it should be converted to two's complement representation first.

**Comment by ehildenb** [comment]
Done, it's included in data.md.
