### ISSUE TITLE
Memoize the decoded code

### ISSUE THREAD

**Issue by yzhang90** [kframework/evm-semantics#180]
Now everytime CALL opcode is used, it will call #asMapOpcodes to decode the byte code. Vyper implement the internal function call using the CALL opcode. And as a result, a lot time is spent on decoding same code again and again. Can we do something about it?

**Comment by ehildenb** [comment]
Newest K Java backend will cache all functions anyway, so this should be fixed. If it's a problem for the OCaml backend (which I don't believe it is), we can add the `memo` attribute.
