### ISSUE TITLE
Build issue due to ocaml and gcc mismatch

### ISSUE THREAD

**Issue by danr** [kframework/evm-semantics#220]
I'm running `gcc` 8.10 so I bump into an issue when the ocaml part of running `make deps` starts. The issue was fixed in this commit in ocaml: https://github.com/ocaml/ocaml/commit/ebcc2f8594138a5ba6b020083fc42d57a914433f
  
Is there a way to install with a newer ocaml version which includes this commit?

Thanks!

**Comment by dwightguth** [comment]
Hi,

Not all of our OCAML dependencies have yet been updated for the latest version of OCAML. Using the latest release of OCAML is something I've been thinking about off and on recently, but it looks like the commit you want is not yet part of any stable release of OCAML, so I'm inclined to wait until it is, which may be a while. In the meantime, I'm going to backport the commit you mention into our set of patches for the OCAML compiler we use for K, which should hopefully fix your issue. I'll update you when this is finished.

**Comment by dwightguth** [comment]
The latest version of k which is included in the latest version of the evm semantics has been tested on a machine with gcc 8.10 and ocaml builds and everything works as far as I'm aware. So I believe that this should have fixed your issue. If not, please reopen with the new technical details.
