### ISSUE TITLE
Rule case splitting with `requires` instead of matching

### ISSUE THREAD

**Issue by MrChico** [kframework/evm-semantics#224]
As discussed in https://github.com/kframework/evm-semantics/issues/192, when matching the arguments of a rule, K is in some cases not able to infer when two cases are mutually exclusive. 
A workaround is to instead check the arguments using `requires`, and change code blocks like:
```
    rule W0 /Word 0  => 0
    rule W0 /Word W1 => chop( W0 /Int W1 ) requires W1 =/=Int 0
```
to 
```
    rule W0 /Word W1  => 0 requires W1 ==Int 0
    rule W0 /Word W1 => chop( W0 /Int W1 ) requires W1 =/=Int 0
```

**Comment by ehildenb** [comment]
Addressed in #240.
