### ISSUE TITLE
Errors when trying to `make deps` and `make`

### ISSUE THREAD

**Issue by tkazana-eth** [kframework/evm-semantics#297]
System: OS X Mojave 10.14.2

Steps to reproduce: I am just following the instructions from readme:

```
brew tap caskroom/cask caskroom/version
brew cask install java8
brew install automake libtool gmp mpfr pkg-config pandoc maven opam z3

make deps
make
```

Eventually, I am getting two errors: one is the problem with switching ocaml to 4.06.1+k (line 89 of `Makefile`) and the other with the `-match-context-rows 2` flag (line 220 of `Makefile`). The following brutal fix seams working (the building process finishes with no errors), however I am not sure if the result is appropriate:
```
89c89
< 	opam switch 4.06.1+k
---
> 	#opam switch 4.06.1+k
220c220
< 	        && ocamlfind $(OCAMLC) -c -g -w -11-26 -package gmp -package zarith -package uuidm -package ethereum-semantics-plugin-$* -safe-string realdef.ml -match-context-rows 2 \
---
> 	        && ocamlfind $(OCAMLC) -c -g -w -11-26 -package gmp -package zarith -package uuidm -package ethereum-semantics-plugin-$* -safe-string realdef.ml \
```
 (above: diff with original `Makefile`)

**Comment by dwightguth** [comment]
What version of opam does brew install?

**Comment by tkazana-eth** [comment]
It is 2.0.2

**Comment by dwightguth** [comment]
Ah, that explains why it doesn't work, our scripts were written for opam 1.x. Is it possible for you to downgrade somehow? or does brew no longer have access to the old version?

**Comment by tkazana-eth** [comment]
Works for me as well!

**Comment by ehildenb** [comment]
We have a work-around in case the newest instructions don't fix this issue. But the newest instructions in the README coupled with `make deps` should not have this issue anymore.
