### ISSUE TITLE
Implement Petersburg fee schedule

### ISSUE THREAD

**Issue by MrChico** [kframework/evm-semantics#320]
Which is essentially just Constantinople minus EIP-1283

**Comment by dwightguth** [comment]
This is on my todo list, I just haven't gotten around to it yet. It should not be at all hard though if you want to tackle it; we already have a Boolean flag to disable the eip' you just need to make a new schedule that sets it to false.

**Comment by dwightguth** [comment]
Never mind, it seems from reading online that this fork goes live soon, so I will work on this today.

**Comment by MrChico** [comment]
I started implementing this, will make a PR in just a minute
