### ISSUE TITLE
Dump inputs to Z3

### ISSUE THREAD

**Issue by bl4ck5un** [kframework/evm-semantics#326]
The `--debug-z3-queries` option isn't available in `kprove` on master. Is there a way to dump the inputs to Z3 solver when generating proofs?

**Comment by ehildenb** [comment]
Well we can update to newest `master`, or you could also use `--state-log --state-log-events Z3QUERY,Z3RESULT --output json`, which will dump a structured log of the Z3 queries (will need a tool which reads it and displays the JSON blobs for you, KLab can do this).

**Comment by ehildenb** [comment]
https://github.com/kframework/evm-semantics/pull/327

**Comment by ehildenb** [comment]
You'll now have both options available. `--state-log` for structured logs which are machine readable, and `--debug-z3-queries` for unstructured human readable logs.

**Comment by bl4ck5un** [comment]
Thanks a lot.
