### ISSUE TITLE
README: invalid ./kevm prove spec location and nonexistent argument of ./kevm test

### ISSUE THREAD

**Issue by chenIshi** [kframework/evm-semantics#357]
In current README.md, 
`./kevm prove tests/proofs/specs/vyper-erc20/totalSupply-spec.k` the location should be tests/specs/......

And also I do not see the entry point of `./kevm test` in script, do `./kevm` still support the usage of `./kevm test ...` ?
(ex: `./kevm test tests/ethereum-tests/VMTests/vmArithmeticTest/add0.json` in README.md)

_Originally posted by @chenIshi in https://github.com/kframework/evm-semantics/issues/159#issuecomment-493839554_

**Comment by ehildenb** [comment]
`./kevm test` is no longer available, all testing is handled in the Makefile.

I've updated https://github.com/kframework/evm-semantics/pull/356 to include these fixes.
