### ISSUE TITLE
HKG with Haskell - Lemmas that use reflection

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/evm-semantics#725]
The Haskell backend does not handle reflection and crashes.

https://github.com/kframework/evm-semantics/blob/master/tests/specs/erc20/abstract-semantics-segmented-gas.k#L20
https://github.com/kframework/evm-semantics/blob/master/tests/specs/erc20/abstract-semantics-segmented-gas.k#L35
https://github.com/kframework/evm-semantics/blob/master/tests/specs/erc20/verification.k#L14

**Comment by denis-bogdanas** [comment]
@virgil-serbanuta These were fixed in VSC. If you look at commit history you'll find the right commit.

**Comment by ehildenb** [comment]
@denis-bogdanas please upstream this fix to KEVM.

**Comment by ehildenb** [comment]
Or at least provide a pointer to the right commit.

We need to stop doing work only in VSC where it gets lost.

**Comment by denis-bogdanas** [comment]
https://github.com/runtimeverification/verified-smart-contracts/commit/1092b584bf8c2e3dd0e8af79445da7409b0b572f

**Comment by denis-bogdanas** [comment]
I can work on this tomorrow if no one else started. Just let me know.

**Comment by ehildenb** [comment]
@denis-bogdanas I've assigned you to this one, and removed @yzhang90 as assignee. Let's make sure when we're working on tasks for this that we assign/unassign each other to make sure no progress is duplicated between people.

Please focus on KEVM, not on VSC. Our goal is to make new proofs work with haskell backend, not migrate all old proofs over. Smaller test-suite in KEVM is the focus.

@yzhang90 of course let us know if you've already made progress on this.

**Comment by yzhang90** [comment]
No. I haven't started to work on this yet.
