### ISSUE TITLE
Some neuance that perhaps should be included in the README.

### ISSUE THREAD

**Issue by barrywhitehat1** [kframework/evm-semantics#74]
I needed the export the following variables to make the install progress

```
 export PATH=~/formalMethods/k/bin:$PATH
export K_VERSION=uiuck
 export PATH=~/formalMethods/pandoc-tangle/bin:$PATH
```
https://github.com/ehildenb/pandoc-tangle, libxml2-utils  is required should be listed in README.md as requirements. Also the above exports should be listed there. 

I am still having trouble building this. When i install k i used the latest releases K 4.0 which does not include the KRYPTO packages https://github.com/kframework/k/pull/2318 

I tried to use develop version of k but am having trouble building that. Which I raised https://github.com/kframework/k/issues/2326

But I think the README should be more explicit about the version of K that is required.

**Comment by ehildenb** [comment]
We'll include these fixes in the `cleanup` PR that we have open. I think we've addressed the issues with `pandoc-tangle`, `libxml2-utils`, and have a fix in the works for the K versioning. Can you checkout the `cleanup` branch and let me know if it addresses your issues?

**Comment by ehildenb** [comment]
If you do `./Build run *`, then the `*` gets interpreted by Bash as globbing (hence it picking up the file `analysis.md`). You should do `./Build run '*'` for the `*` to be passed to `grep` for determining which tests to run.

**Comment by ehildenb** [comment]
But doing `./Build run` should only be done for a specific file, eg. `./Build run tests/VMTests/vmArithmeticTest/add0.json`. Should do something like `./Build test-all` to run all the tests (if that's what you're trying to do). Run `./Build help` to see the list of available tests.

**Comment by ehildenb** [comment]
Closing because the latest PR include documentation about this.
Feel free to re-open if you feel it's not sufficient.
