### ISSUE TITLE
StackOverflowError while proving `transfer-failure-1-a-spec.k`

### ISSUE THREAD

**Issue by alex-chambet** [kframework/evm-semantics#792]
I built the KEVM and tried to run the command given at the end, namely `./kevm prove tests/specs/erc20/ds/transfer-failure-1-a-spec.k VERIFICATION` and I have a StackOverflowError.

The output is:
```
[Error] Critical: Function evaluation triggered infinite recursion. Trace:
(StackOverflowError: null)
while evaluating function keccak
while evaluating function keccakIntList
while evaluating function keccak
while evaluating function keccakIntList
```
(and so on...)

How to fix that?

**Comment by ehildenb** [comment]
You need to provide additional arguments to `./kevm prove` to run that proof. You can do:

```
make tests/specs/erc20/ds/transfer-failur-1-a-spek.k.prove
```

to see the extra arguments needed for that proof.

**Comment by ehildenb** [comment]
In particular, you need the arguments which make `keccak` and `keccakIntList` rules `concrete`, which will stop this infinite recursion.

**Comment by alex-chambet** [comment]
Alright, it's working fine now. Maybe you could add that in the README for the future newcomers, they might find it useful. Thanks!
