### ISSUE TITLE
Building docker file failed

### ISSUE THREAD

**Issue by lukwue** [kframework/evm-semantics#798]
Hi,

I have tried to build the dockerfile. I ran `sudo docker build --tag kevm .`  in the `evm-semantics` folder and at step 3/25 the following error occured: 
```
Step 3/25 : ADD deps/k/haskell-backend/src/main/native/haskell-backend/scripts/install-stack.sh /.install-stack/
ADD failed: stat /var/snap/docker/common/var-lib-docker/tmp/docker-builder953740166/deps/k/haskell-backend/src/main/native/haskell-backend/scripts/install-stack.sh: no such file or directory
```
My versions are: `ubuntu 20.04`

Docker: `Docker version 18.09.9, build 1752eb3`

Thank you :)

**Comment by ehildenb** [comment]
You probably need to do `git submodule update --init --recursive` before attempting to build the docker file.

If this solves your issue, please close.

**Comment by lukwue** [comment]
Hello,

thank you. The error did not occur anymore but another one:
`Error processing tar file(exit status 1): write /usr/lib/llvm-8/lib/clang/8.0.0/lib/linux/libclang_rt.esan-x86_64.a: no space left on device
`
This is the whole error output which was still on my terminal:

[error_kevm.TXT](https://github.com/kframework/evm-semantics/files/4655807/error_kevm.TXT)

Do you know a possible reason for that? I use a virtual machine with 35 GB disk space and I am sure I have not used more than 10 GB so far. 
This is my output when I run `df -h` :
![df](https://user-images.githubusercontent.com/63459921/82429501-4dd31700-9a8c-11ea-8ce7-d3b990a40f31.PNG)

**Comment by lukwue** [comment]
Thank you, that did the trick :)
