### ISSUE TITLE
Clarify what kind of arguments ./Build run can take

### ISSUE THREAD

**Issue by pirapira** [kframework/evm-semantics#91]
README.md has the following line:
> Use ./Build run <file> and ./Build test <file> to run/test a file, respectively.

It was not obvious to me that `<file>` cannot be `ethereum.md`.  So I tried `./Build test ethereum.md` but [it did not work](https://github.com/kframework/evm-semantics/issues/89).

So some description about `<file>` would be helpful here.

**Comment by ehildenb** [comment]
Check branch `documentation-cleanup` and see if it is satisfying.

**Comment by ehildenb** [comment]
Hmmm, actually, let me clarify it even more.

**Comment by ehildenb** [comment]
Please look again, see if the output of `./Build help` seems more reasonable on branch `documentation-cleanup`

**Comment by pirapira** [comment]
Looks satisfactory.  With all the examples, it's clear what I can put as the argument.

I'll close this issue, no further attention necessary except on your PR.
