### ISSUE TITLE
Proofs use wrong PC values / PC extraction methodology

### ISSUE THREAD

**Issue by pdaian** [kframework/evm-semantics#94]
Hi all,

Upon inspecting several of the proofs currently in the evm-semantics repo and attempting to reproduce them with my own token code, I've noticed several minor inconsistencies between what we claim to prove and what we are actually proving.

The inconsistencies are introduced by the current proving methodology, which as described to me involves:
1. Compile some Solidity code to EVM and include this in the specification.
2. Run the same contract in the Remix IDE, and extract the PC values that cover the relevant target function.
3. Run a partial specification including these PC values through the IntelliJ debugger, and use to extract concrete constants for things like gas consumption.

The core problem with the current specification is that, in several of them, the PC value being used is not the correct PC value as specified by the jump-table in the contract.  This is introduced from a surprising interaction between the above steps.  Specifically, it is often case that **the built-in compiler used in step 2 (Remix) is not the same version as the compiler used to generate the bytecode being proved**.  This can result in PC values being "shifted", and the wrong PC values can be used in the specification.  This issue was confirmed: I was able to reproduce several of the wrong PC values used in the specification by compiling with a different version of solc on Remix.  Because Remix is dynamically updated, it is possible that such updates were deployed during the development of the spec.  If the bytecode was copied over early in development and the PC values were obtained later, this would explain the discrepancies.

In practice, what this means is that *many of our proofs start from the middle of a function*, skipping some validation steps.  What we are proving is not wrong, but it is not exactly what we claim to prove in that it does not include the full code of the function.  This "missed code", either at the beginning or end of a function, could potentially violate properties in our proofs.  Furthermore, some values in our proof, for example the gas costs, are incorrect in many of the specifications.

| **Function** | **Function Signature (ABI)** | **Jump Table Function Start (BC)** | **Function End (BC)** | **Spec Function Start** | **Spec Function End**           |
|--------------|--------------------------|--------------------------------|-------------------|---------------------|-----------------------------|
| transfer     | 0xa9059cbb               | 0x17e / 382                    | 0x1d4 / 468       | 0x5fd / 1533        | 0x6ec / 1772 [0x764 / 1892] |
| transferFrom | 0x23b872dd               | 0xbe / 190                     | 0x133 / 307       | 0x332 / 818         | 0x533 / 1331 [0x5ab / 1451] |
| balanceOf    | 0x70a08231               | 0x134 / 308                    | 0x17d / 381       | 0x13c / 316         | 0x17d / 381                 |
| allowance    | 0xdd62ed3e               | 0x1d5 / 469                    | 0x23d / 573       | 0x1d5 / 469         | 0x23d / 573                 |
| approve      | 0x095ea7b3               | 0x67 / 103                     | 0xbd / 189        | 0x23e / 574         | 0x32a / 810                 |

The table above summarizes the discrepancies between the program counter values used in the specification and the program counter values obtained by manually decompiling the provided bytecode.  The function start (BC) value is the value that the program counter is set to based on the function selector, specified in the jump table at the beginning of the bytecode and selected by the function selector.  The end value is the result of manually tracing the decompiled bytecode until the RETURN opcode is reached, indicating the end of a function.  The specification values are lifted from the PC cell in each corresponding specification.  Some functions are covered by multiple specifications, like transfer; we use brackets to distinguish between the PC values of these cases in the specification.

The above shows that only one specification is using proper values, for approve.

Consequences
------------------

The above may seem purely academic, but it has some important practical consequences.  I only tested one specification manually to see what was being omitted, the balanceOf specification.  Several of the function modifier checks were omitted, including the default check that Solidity adds to every non-payable function to make sure it is not sent Ether balance.

The current specification gives ``<callValue>    0            </callValue>``, and executes the balanceOf function assuming the call value (msg.value) is 0.  Changing this to ``<callValue>    50            </callValue>`` allows the proof to still succeed, and the prover outputs true on the property.

**This property is however wrong**.  Calling the balanceOf function with a non-zero call value will throw in the production contract (and indeed in the bytecode being verified).

It is likely many of these specifications will allow you to prove similarly incorrect results over their target functions with some minor modification.  In addition, the concrete gas bounds we derive (which may be considered as part of the property) are again wrong in every case but approve, as the full function code is not executed.

Solution
-----------

Several remediations are possible.  One is ABI-level proving, which would nicely solve this issue.  In fact, the properties we've proved here would in most cases fail to verify at the ABI level.  This anecdotal example can also serve to motivate ABI-level verification.

Another possible solution is a tool automatically extracting PC locations from bytecode for a given function / function identifier.  Using this rather than remix in our proofs will likely solve this issue.

**Comment by grosu** [comment]
Thanks so much, @pdaian !  This is very useful.  We knew that there was "glue" code that was not verified, but your detailed explanation makes it clear now.  We are now moving towards ABI-level verification, which will hopefully solve the problem, as you also suggested above.

**Comment by dwightguth** [comment]
Fixed in #139
